[package]
name = "memdb-socket"
version = "0.1.0"
edition = "2021"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[dependencies]
socket2 = "0.4.0"
libc = "0.2"
rand = "0.8.4"
tokio = "1.40.0"
